### PR TITLE
Updated code to PHP 8.1 standards and some fixes

### PR DESCRIPTION
**Pull request by algirdas-iterato**
PHP 7 has already reached its EOL. So, here is the upgrade to PHP 8.1 and some additional improvements. There is no braking changes (except version upgrade), only minor changes and fixes.

- Updated code to PHP 8.1 standards
- Fixed some typos
- Fixed bug related to Codec8Extended
- Added docker and makefile for development commands
- Added phpstan and did changes by it
- Added php-cs-fixer and did changes by it

### CODE REVIEW

**Comment by kemalovski** [comment]
Downloaded and and tested. 
It's work fine and beautiful. 
Good job bro!
@algirdas-iterato 
@uro

**Comment by algirdas-iterato** [comment]
@uro maybe you could take a look at this PR?

**Comment by uro** [comment]
Doing now, thank you @algirdas-iterato

**Comment by uro** [comment]
Hey @algirdas-iterato 
I just remembered one more thing. Could you please update the readme file? 
Thanks

**Pull request merged**
